from __future__ import annotations

from pathlib import Path

from .models import Finding, ScanResult


SEVERITY_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
def render_console(result: ScanResult) -> None:
    print(f"AI Web Auditor {result.version}")
    print(f"Target: {result.target.normalized_url}")
    print(f"Status: {result.status} | Generated: {result.generated_at}")
    print()

    print("Modules")
    print("-------")
    for module in result.modules:
        print(f"- {module.name}: {module.status} - {module.summary}")

    findings = sorted(result.findings, key=lambda item: SEVERITY_RANK.get(item.severity, 99))
    if not findings:
        print()
        print("No findings generated by the enabled modules.")
        return

    print()
    print("Findings")
    print("--------")
    for finding in findings:
        print(f"- {finding.severity.upper()} {finding.id}: {finding.title}")
        print(f"  Target: {finding.target}")

    print()
    print("Recommendations")
    print("---------------")
    for finding in findings:
        _render_finding_detail(finding)


def write_json(result: ScanResult, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(result.to_json(indent=2) + "\n", encoding="utf-8")


def _render_finding_detail(finding: Finding) -> None:
    print(f"{finding.severity.upper()} {finding.id}: {finding.title}")
    print(f"  {finding.description}")
    print(f"  Recommendation: {finding.recommendation}")
    for evidence in finding.evidence[:3]:
        location = f" ({evidence.location})" if evidence.location else ""
        print(f"  Evidence - {evidence.label}{location}: {evidence.value}")
