from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from . import __version__
from .models import utc_now


SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
    "informational": 4,
}


def load_json_file(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON root must be an object: {path}")
    return data


def generate_markdown_report(
    scan_data: dict[str, Any],
    *,
    ai_analysis: dict[str, Any] | None = None,
    title: str | None = None,
) -> str:
    target = scan_data.get("target") if isinstance(scan_data.get("target"), dict) else {}
    findings = _findings(scan_data)
    modules = _modules(scan_data)
    ai_body = _analysis_body(ai_analysis)
    report_title = title or f"Web Audit Report - {_value(target.get('host'), 'unknown target')}"

    lines: list[str] = [
        f"# {report_title}",
        "",
        f"- Generated: {utc_now()}",
        f"- Report generator: ai-web-auditor {__version__}",
        f"- Scan version: {_value(scan_data.get('version'), 'unknown')}",
        f"- Scan status: {_value(scan_data.get('status'), 'unknown')}",
        "",
        "## Target",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Original URL | {_cell(target.get('original_url'))} |",
        f"| Normalized URL | {_cell(target.get('normalized_url'))} |",
        f"| Host | {_cell(target.get('host'))} |",
        f"| Scheme | {_cell(target.get('scheme'))} |",
        f"| Port | {_cell(target.get('port'))} |",
        "",
    ]

    lines.extend(_executive_summary_section(findings, ai_body))
    lines.extend(_severity_summary_section(findings))
    lines.extend(_module_summary_section(modules))
    lines.extend(_findings_section(findings))
    lines.extend(_technology_section(modules))
    lines.extend(_crawler_section(modules))
    lines.extend(_ai_section(ai_body))
    lines.extend(_limitations_section(ai_body))

    return "\n".join(lines).rstrip() + "\n"


def write_markdown_report(markdown: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")


def _executive_summary_section(findings: list[dict[str, Any]], ai_body: dict[str, Any] | None) -> list[str]:
    if ai_body and ai_body.get("executive_summary"):
        summary = str(ai_body["executive_summary"])
        risk_level = ai_body.get("risk_level", "unknown")
        rationale = ai_body.get("risk_rationale", "No rationale provided.")
        return [
            "## Executive Summary",
            "",
            summary,
            "",
            f"Overall risk: **{_text(risk_level)}**",
            "",
            _text(rationale),
            "",
        ]

    counts = Counter(_severity(finding) for finding in findings)
    if not findings:
        summary = "No findings were generated by the enabled modules."
    else:
        summary = (
            f"The scan generated {len(findings)} finding(s): "
            f"{counts.get('critical', 0)} critical, {counts.get('high', 0)} high, "
            f"{counts.get('medium', 0)} medium, {counts.get('low', 0)} low and "
            f"{counts.get('info', 0) + counts.get('informational', 0)} informational."
        )
    return ["## Executive Summary", "", summary, ""]


def _severity_summary_section(findings: list[dict[str, Any]]) -> list[str]:
    counts = Counter(_severity(finding) for finding in findings)
    severities = ["critical", "high", "medium", "low", "info"]
    lines = [
        "## Severity Summary",
        "",
        "| Severity | Count |",
        "| --- | ---: |",
    ]
    for severity in severities:
        count = counts.get(severity, 0)
        if severity == "info":
            count += counts.get("informational", 0)
        lines.append(f"| {severity.upper()} | {count} |")
    lines.append("")
    return lines


def _module_summary_section(modules: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Module Summary",
        "",
        "| Module | Status | Summary |",
        "| --- | --- | --- |",
    ]
    for module in modules:
        lines.append(
            f"| {_cell(module.get('name'))} | {_cell(module.get('status'))} | {_cell(module.get('summary'))} |"
        )
    lines.append("")
    return lines


def _findings_section(findings: list[dict[str, Any]]) -> list[str]:
    lines = ["## Findings", ""]
    if not findings:
        lines.extend(["No findings were reported.", ""])
        return lines

    for finding in sorted(findings, key=lambda item: (SEVERITY_ORDER.get(_severity(item), 99), str(item.get("id", "")))):
        lines.extend(
            [
                f"### {_text(finding.get('severity', 'info')).upper()} - {_text(finding.get('title', 'Untitled finding'))}",
                "",
                f"- ID: `{_text(finding.get('id', 'unknown'))}`",
                f"- Category: {_text(finding.get('category', 'unknown'))}",
                f"- Module: `{_text(finding.get('module', 'unknown'))}`",
                f"- Target: `{_text(finding.get('target', 'unknown'))}`",
                "",
                "**Description**",
                "",
                _text(finding.get("description", "No description provided.")),
                "",
                "**Recommendation**",
                "",
                _text(finding.get("recommendation", "No recommendation provided.")),
                "",
            ]
        )
        evidence = finding.get("evidence")
        if isinstance(evidence, list) and evidence:
            lines.extend(["**Evidence**", ""])
            for item in evidence:
                if not isinstance(item, dict):
                    continue
                label = _text(item.get("label", "evidence"))
                value = _text(item.get("value", ""))
                location = item.get("location")
                suffix = f" ({_text(location)})" if location else ""
                lines.append(f"- {label}{suffix}: `{value}`")
            lines.append("")
    return lines


def _technology_section(modules: list[dict[str, Any]]) -> list[str]:
    fingerprinting = _module_by_name(modules, "fingerprinting")
    if not fingerprinting:
        return []

    artifacts = fingerprinting.get("artifacts") if isinstance(fingerprinting.get("artifacts"), dict) else {}
    technologies = artifacts.get("technologies") if isinstance(artifacts.get("technologies"), list) else []
    public_files = artifacts.get("public_files") if isinstance(artifacts.get("public_files"), list) else []
    lines = ["## Technology Fingerprinting", ""]

    if technologies:
        lines.extend(["| Technology | Category | Confidence | Signals |", "| --- | --- | --- | --- |"])
        for technology in technologies:
            if not isinstance(technology, dict):
                continue
            signals = technology.get("signals") if isinstance(technology.get("signals"), list) else []
            name = technology.get("name")
            version = technology.get("version")
            display_name = f"{name} {version}" if version else name
            lines.append(
                f"| {_cell(display_name)} | {_cell(technology.get('category'))} | {_cell(technology.get('confidence'))} | {_cell(', '.join(map(str, signals)))} |"
            )
        lines.append("")
    else:
        lines.extend(["No technology signals were identified.", ""])

    if public_files:
        lines.extend(["### Public Metadata Files", "", "| Path | Status | Present |", "| --- | ---: | --- |"])
        for item in public_files:
            if isinstance(item, dict):
                lines.append(
                    f"| {_cell(item.get('path'))} | {_cell(item.get('status_code', item.get('status')))} | {_cell(item.get('present'))} |"
                )
        lines.append("")
    return lines


def _crawler_section(modules: list[dict[str, Any]]) -> list[str]:
    crawler = _module_by_name(modules, "crawler")
    if not crawler:
        return []

    artifacts = crawler.get("artifacts") if isinstance(crawler.get("artifacts"), dict) else {}
    fetched = _string_list(artifacts.get("fetched_urls"))
    discovered = _string_list(artifacts.get("discovered_urls"))
    out_of_scope = _string_list(artifacts.get("out_of_scope_urls"))
    excluded = _string_list(artifacts.get("excluded_urls"))

    lines = [
        "## Crawler",
        "",
        f"- Seed URL: `{_text(artifacts.get('seed_url', 'unknown'))}`",
        f"- Max depth: {_text(artifacts.get('max_depth', 'unknown'))}",
        f"- Max pages: {_text(artifacts.get('max_pages', 'unknown'))}",
        f"- Fetched URLs: {len(fetched)}",
        f"- Discovered in-scope URLs: {len(discovered)}",
        f"- Out-of-scope URLs recorded but not visited: {len(out_of_scope)}",
        f"- Excluded URLs recorded but not visited: {len(excluded)}",
        "",
    ]

    if discovered:
        lines.extend(["### Discovered URLs", ""])
        lines.extend(f"- `{url}`" for url in discovered[:50])
        if len(discovered) > 50:
            lines.append(f"- ... {len(discovered) - 50} more")
        lines.append("")

    if out_of_scope:
        lines.extend(["### Out-of-Scope URLs", ""])
        lines.extend(f"- `{url}`" for url in out_of_scope[:25])
        lines.append("")

    if excluded:
        lines.extend(["### Excluded URLs", ""])
        lines.extend(f"- `{url}`" for url in excluded[:25])
        lines.append("")

    return lines


def _ai_section(ai_body: dict[str, Any] | None) -> list[str]:
    if not ai_body:
        return []

    lines: list[str] = []
    priority_findings = ai_body.get("priority_findings")
    if isinstance(priority_findings, list) and priority_findings:
        lines.extend(["## AI Prioritization", ""])
        for item in priority_findings:
            if not isinstance(item, dict):
                continue
            lines.extend(
                [
                    f"### {item.get('rank', '?')}. {_text(item.get('title', 'Untitled'))}",
                    "",
                    f"- Severity: {_text(item.get('severity', 'unknown'))}",
                    f"- Why it matters: {_text(item.get('why_it_matters', 'No explanation provided.'))}",
                    f"- Recommended action: {_text(item.get('recommended_action', 'No action provided.'))}",
                    "",
                ]
            )
            evidence = item.get("evidence")
            if isinstance(evidence, list) and evidence:
                lines.extend(["Evidence:", ""])
                lines.extend(f"- {_text(value)}" for value in evidence)
                lines.append("")

    safe_next_steps = ai_body.get("safe_next_steps")
    if isinstance(safe_next_steps, list) and safe_next_steps:
        lines.extend(["## Safe Next Steps", ""])
        lines.extend(f"- {_text(step)}" for step in safe_next_steps)
        lines.append("")

    report_notes = ai_body.get("report_notes")
    if isinstance(report_notes, list) and report_notes:
        lines.extend(["## Report Notes", ""])
        lines.extend(f"- {_text(note)}" for note in report_notes)
        lines.append("")

    return lines


def _limitations_section(ai_body: dict[str, Any] | None) -> list[str]:
    lines = [
        "## Limitations",
        "",
        "- This report is based on non-intrusive checks only.",
        "- No exploitation, brute force, aggressive fuzzing or destructive testing was performed.",
        "- Findings should be validated against the authorized scope and business context.",
    ]

    if ai_body:
        limitations = ai_body.get("limitations")
        if isinstance(limitations, list):
            lines.extend(f"- {_text(item)}" for item in limitations)
    lines.append("")
    return lines


def _analysis_body(ai_analysis: dict[str, Any] | None) -> dict[str, Any] | None:
    if not ai_analysis:
        return None
    body = ai_analysis.get("analysis")
    return body if isinstance(body, dict) else ai_analysis


def _findings(scan_data: dict[str, Any]) -> list[dict[str, Any]]:
    findings = scan_data.get("findings")
    return [item for item in findings if isinstance(item, dict)] if isinstance(findings, list) else []


def _modules(scan_data: dict[str, Any]) -> list[dict[str, Any]]:
    modules = scan_data.get("modules")
    return [item for item in modules if isinstance(item, dict)] if isinstance(modules, list) else []


def _module_by_name(modules: list[dict[str, Any]], name: str) -> dict[str, Any] | None:
    for module in modules:
        if module.get("name") == name:
            return module
    return None


def _severity(finding: dict[str, Any]) -> str:
    severity = str(finding.get("severity", "info")).lower()
    return "info" if severity == "informational" else severity


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def _cell(value: Any) -> str:
    return _text(value).replace("|", "\\|").replace("\n", "<br>")


def _text(value: Any) -> str:
    return str(_value(value, "unknown")).replace("\r\n", "\n").replace("\r", "\n").strip()


def _value(value: Any, default: str) -> Any:
    return default if value is None or value == "" else value
